{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Exception Handling"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "An exception or logical error is an unexpected event that occurs during program execution(runtime).\n",
    "\n",
    "Whenever exception occurs python creates exception object and `raise` exception.\n",
    "\n",
    "If not handled properly, interpreter prints a traceback to that error along with details of cause of error and exception type.\n",
    "\n",
    "We can handle error using `try, except` and `finally` statements."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exceptions vs Errors"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Errors represent the issue with the code which cant be handled at runtime, such as compilation error, syntax error, logical error, incompatibility issue.\n",
    "\n",
    "Exception can be caught and handled by us.\n",
    "\n",
    "Conditions that occurs in syntactically correct python code at runtime which can be handled are exceptions.\n",
    "\n",
    "In case of  error the arrow indicates where the error is and what error it is, while in case of exception a message shows the type of exception."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "unmatched ')' (54831354.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[4], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    print(0/0))  # syntax error\u001b[0m\n\u001b[1;37m              ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m unmatched ')'\n"
     ]
    }
   ],
   "source": [
    "print(0/0))  # syntax error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[5], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m0\u001b[39;49m \u001b[39m/\u001b[39;49m \u001b[39m0\u001b[39;49m)\n",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "print(0 / 0) # exception error"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Built-in Exceptions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Python comes with various built-in exceptions as well as we have ability to device our custom exceptions.\n",
    "\n",
    "All exceptions must be instances of a class that derives from  `BaseException` class. \n",
    "\n",
    "In a `try.` statement with `except` clause that mentions a particular class, that clause also handles any exception classes derived from that class (but not exception classes from which its is derived). Two exception classes that are not related via subclassing are never equivalent, even if they have the same name.\n",
    "\n",
    "The built-in exceptions can be generated by the interpreter or built-in functions, except where they have associate value(error code: it may be string, tuple) indicating the detailed cause of the error and this associate value is usually passed as arguments to the exception class's constructor.\n",
    "\n",
    "User code can `raise` built-in exception. This can be used:\n",
    "    - Either test an exception handler \n",
    "    - or to report an error condition \n",
    "    - or to do something else in case of exception and raise the exception\n",
    "\n",
    "The built-in exception classes can be subclassed to define new exceptions; programmers are encouraged to derive new exception from teh `Exception` class or one of its subclasses, and not from `BaseException`.\n",
    "\n",
    "\n",
    "**Exception Context**\n",
    "\n",
    "When raising a new exception while another exception is already being handled, the new exception's `__context__` attribute is automatically set to the handled exception. An exception may be handled when an `except` or `finally` clause, or a `with`  statement is used.\n",
    "\n",
    "This implicit exception context can be supplemented with an explicit cause by using from with raise:\n",
    "\n",
    "```\n",
    "raise new_exception from original_exception\n",
    "```\n",
    "\n",
    "After doing this a chained exception traceback is show with new exception and after that the older one.\n",
    "\n",
    "*Most built-in exceptions are implemented in C for efficiency.  refer: [ Objects/exceptions.c](https://github.com/python/cpython/blob/3.11/Objects/exceptions.c)*"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exception hierarchy(Built-in)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "These are built-in exceptions in python in hierarchial order of classes.\n",
    "\n",
    "```\n",
    "BaseException\n",
    " ├── BaseExceptionGroup\n",
    " ├── GeneratorExit\n",
    " ├── KeyboardInterrupt\n",
    " ├── SystemExit\n",
    " └── Exception\n",
    "      ├── ArithmeticError\n",
    "      │    ├── FloatingPointError\n",
    "      │    ├── OverflowError\n",
    "      │    └── ZeroDivisionError\n",
    "      ├── AssertionError\n",
    "      ├── AttributeError\n",
    "      ├── BufferError\n",
    "      ├── EOFError\n",
    "      ├── ExceptionGroup [BaseExceptionGroup]\n",
    "      ├── ImportError\n",
    "      │    └── ModuleNotFoundError\n",
    "      ├── LookupError\n",
    "      │    ├── IndexError\n",
    "      │    └── KeyError\n",
    "      ├── MemoryError\n",
    "      ├── NameError\n",
    "      │    └── UnboundLocalError\n",
    "      ├── OSError\n",
    "      │    ├── BlockingIOError\n",
    "      │    ├── ChildProcessError\n",
    "      │    ├── ConnectionError\n",
    "      │    │    ├── BrokenPipeError\n",
    "      │    │    ├── ConnectionAbortedError\n",
    "      │    │    ├── ConnectionRefusedError\n",
    "      │    │    └── ConnectionResetError\n",
    "      │    ├── FileExistsError\n",
    "      │    ├── FileNotFoundError\n",
    "      │    ├── InterruptedError\n",
    "      │    ├── IsADirectoryError\n",
    "      │    ├── NotADirectoryError\n",
    "      │    ├── PermissionError\n",
    "      │    ├── ProcessLookupError\n",
    "      │    └── TimeoutError\n",
    "      ├── ReferenceError\n",
    "      ├── RuntimeError\n",
    "      │    ├── NotImplementedError\n",
    "      │    └── RecursionError\n",
    "      ├── StopAsyncIteration\n",
    "      ├── StopIteration\n",
    "      ├── SyntaxError\n",
    "      │    └── IndentationError\n",
    "      │         └── TabError\n",
    "      ├── SystemError\n",
    "      ├── TypeError\n",
    "      ├── ValueError\n",
    "      │    └── UnicodeError\n",
    "      │         ├── UnicodeDecodeError\n",
    "      │         ├── UnicodeEncodeError\n",
    "      │         └── UnicodeTranslateError\n",
    "      └── Warning\n",
    "           ├── BytesWarning\n",
    "           ├── DeprecationWarning\n",
    "           ├── EncodingWarning\n",
    "           ├── FutureWarning\n",
    "           ├── ImportWarning\n",
    "           ├── PendingDeprecationWarning\n",
    "           ├── ResourceWarning\n",
    "           ├── RuntimeWarning\n",
    "           ├── SyntaxWarning\n",
    "           ├── UnicodeWarning\n",
    "           └── UserWarning\n",
    "\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Warnings"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`Warnings` are special type of exceptions which are issued to alert the user of some condition in a program, where that condition doesn't warrant raising an exception and terminating the program. \n",
    "\n",
    "Warnings are issued using  `warn()`function.\n",
    "\n",
    "All warning types are mentioned above.\n",
    "\n",
    "**Warning Filter**\n",
    "The warnings filter controls whether warnings are ignored, displayed, or turned into errors (raising an exception).\n",
    "\n",
    "Conceptually, the warnings filter maintains an ordered list of filter specifications; any specific warning is matched against each filter specification in the list in turn until a match is found; the filter determines the disposition of the match. Each entry is a tuple of the form (action, message, category, module, lineno), where:\n",
    "\n",
    "- `action` is one of the following strings:\n",
    "  - `default`: print the first occurrence of matching warnings for each location (module + line number) where the warning is issued\n",
    "  - `error`: turn matching warnings into exceptions\n",
    "  - `ignore`: never print matching warnings\n",
    "  - `always`: always print matching warnings\n",
    "  - `module`: print the first occurrence of matching warnings for each module where the warning is issued (regardless of line number)\n",
    "  - `once`: print only the first occurrence of matching warnings, regardless of location\n",
    "\n",
    "- `message` is a string containing a regular expression that the start of the warning message must match, case-insensitivity.\n",
    "- `category` is a class (a sub class of `Warning`) of which the warning category must be subclass in order to match.\n",
    "- `module`:  is a string containing a regular expression that the start of the fully qualified module name must match, case-sensitively. \n",
    "- `lineno` is an integer that the line number where the warning occurred must match, or 0 to match all line numbers.\n",
    "\n",
    "Since the `Warning` class is derived from the built-in `Exception` class, to turn a warning into an error we simply `raise category(message)`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "warnings.simplefilter('ignore')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Custom Exceptions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Custom exceptions can be defined by creating subclasses that inherit from an exception type.\n",
    "\n",
    "We can define our custom exception as:\n",
    "```\n",
    "class CustomException(Exception):\n",
    "    pass\n",
    "\n",
    "try:\n",
    "    pass\n",
    "except CustomException:\n",
    "    pass\n",
    "```\n",
    "\n",
    "*Its recommended to device a subclass only inheriting from a single exception class for clarity purpose and to avoid any possible conflicts between how the base class handles that error an how the other classes handle it*\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "\n",
    "\n",
    "def error_message_detail(error, error_detail: sys):\n",
    "    \"\"\"\n",
    "    Extract error causing scripts, error causing line, error\n",
    "    --------------------------------------------------------\n",
    "    error: from RULException class\n",
    "    error_detail: from RULException class\n",
    "    ---------------------------------------------------------\n",
    "    return: error_message\n",
    "    \"\"\"\n",
    "\n",
    "    # exc_tb : exception traceback\n",
    "    _, _, exc_tb = error_detail.exc_info()\n",
    "    file_name = exc_tb.tb_frame.f_code.co_filename\n",
    "    error_message = \"Python script: [{0}] Line number: [{1}]  Error message: [{2}]\".format(file_name, exc_tb.tb_lineno, str(error))\n",
    "\n",
    "    return error_message\n",
    "    \n",
    "    \n",
    "\n",
    "class RULException(Exception):\n",
    "    \"\"\"\n",
    "    Raise RULException\n",
    "    ---------------------------------------------------------\n",
    "    `error`: from error_message_detail function\n",
    "    `error_detail`: from error_message_detail function\n",
    "    ---------------------------------------------------------\n",
    "    return: RUL exception error message\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, error_message, error_detail:sys):\n",
    "        self.error_message = error_message_detail(error=error_message, error_detail=error_detail)\n",
    "    \n",
    "    def __str__(self) -> str:\n",
    "        return self.error_message"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "ename": "RULException",
     "evalue": "Python script: [C:\\Users\\abhij\\AppData\\Local\\Temp\\ipykernel_1452\\2591893850.py] Line number: [3]  Error message: [division by zero]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[29], line 3\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m----> 3\u001b[0m     Threshold \u001b[39m+\u001b[39m \u001b[39m10\u001b[39;49m \u001b[39m/\u001b[39;49m \u001b[39m0\u001b[39;49m \u001b[39m==\u001b[39m \u001b[39m0\u001b[39m\n\u001b[0;32m      4\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mRULException\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[29], line 5\u001b[0m\n\u001b[0;32m      3\u001b[0m     Threshold \u001b[39m+\u001b[39m \u001b[39m10\u001b[39m \u001b[39m/\u001b[39m \u001b[39m0\u001b[39m \u001b[39m==\u001b[39m \u001b[39m0\u001b[39m\n\u001b[0;32m      4\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m----> 5\u001b[0m     \u001b[39mraise\u001b[39;00m RULException(e, sys)\n",
      "\u001b[1;31mRULException\u001b[0m: Python script: [C:\\Users\\abhij\\AppData\\Local\\Temp\\ipykernel_1452\\2591893850.py] Line number: [3]  Error message: [division by zero]"
     ]
    }
   ],
   "source": [
    "Threshold = 10\n",
    "try:\n",
    "    Threshold + 10 / 0 == 0\n",
    "except Exception as e:\n",
    "    raise RULException(e, sys)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We can use `raise` to throw an exception if a condition occurs, this statement can be complemented with a custom exception we discussed.\n",
    "\n",
    "Syntax:\n",
    "```\n",
    "if condition:\n",
    "    raise Exception()\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "ename": "Exception",
     "evalue": "Threshold high",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mException\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[30], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m Threshold \u001b[39m=\u001b[39m \u001b[39m10\u001b[39m\n\u001b[0;32m      2\u001b[0m \u001b[39mif\u001b[39;00m Threshold \u001b[39m>\u001b[39m \u001b[39m9.8\u001b[39m:\n\u001b[1;32m----> 3\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mException\u001b[39;00m(\u001b[39m'\u001b[39m\u001b[39mThreshold high\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[1;31mException\u001b[0m: Threshold high"
     ]
    }
   ],
   "source": [
    "Threshold = 10\n",
    "if Threshold > 9.8:\n",
    "    raise Exception('Threshold high')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Instead of waiting for program to crash midway, we can also start by making an assertion in python. We `assert`  that a certain condition is met. If this condition turns out to be True, then that is excellent and program can continue. If condition turns out to be False, we can have the program to throw an `AssertionError` exception.\n",
    "\n",
    "Syntax:\n",
    "```\n",
    "assert(condition)\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "ename": "AssertionError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[31], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39msys\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[39massert\u001b[39;00m(\u001b[39m'\u001b[39m\u001b[39mlinux\u001b[39m\u001b[39m'\u001b[39m \u001b[39min\u001b[39;00m sys\u001b[39m.\u001b[39mplatform)\n",
      "\u001b[1;31mAssertionError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import sys\n",
    "assert('linux' in sys.platform)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exception Handling"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "`try` `except` `finally` block used to handle exceptions\n",
    "\n",
    "Possible configurations for handling exceptions are:\n",
    "```\n",
    "# only try except\n",
    "try:\n",
    "    # code that may cause exception\n",
    "except:\n",
    "    # code to run when exception occurs\n",
    "\n",
    "\n",
    "# multiple except blocks\n",
    "try:\n",
    "    # code that may cause exception\n",
    "except Exception1:\n",
    "    # code that may cause exception type 1\n",
    "except Exception2:\n",
    "    # code that may cause exception type 2\n",
    "\n",
    "\n",
    "# try, except, finally\n",
    "try:\n",
    "    # some code that may cause exception\n",
    "except:\n",
    "    # code to run when exception occurs\n",
    "finally:\n",
    "    # this code will always run no matter exception occurs or not\n",
    "\n",
    "\n",
    "# try, except with else \n",
    "try:\n",
    "    # code that may cause exception\n",
    "except: \n",
    "    # code to run when exception occurs\n",
    "else:\n",
    "    # if exception do this \n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: b cannot be 0.\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    a = 100\n",
    "    b = 0\n",
    "    result = a/b\n",
    "except:\n",
    "    print(\"Error: b cannot be 0.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index Out of Bound.\n"
     ]
    }
   ],
   "source": [
    "# multiple except block\n",
    "try:\n",
    "    even_numbers = [2,4,6,8]\n",
    "    print(even_numbers[5])\n",
    "\n",
    "except ZeroDivisionError:\n",
    "    print(\"Denominator cannot be 0.\")\n",
    "    \n",
    "except IndexError:\n",
    "    print(\"Index Out of Bound.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: b cannot be 0.\n",
      "Finally block.\n"
     ]
    }
   ],
   "source": [
    "# try, except and finally\n",
    "try:\n",
    "    a = 100\n",
    "    b = 0\n",
    "\n",
    "    result = a/b\n",
    "\n",
    "    print(result)\n",
    "except:\n",
    "    print(\"Error: b cannot be 0.\")\n",
    "    \n",
    "finally:\n",
    "    print(\"Finally block.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Not an even number!\n"
     ]
    }
   ],
   "source": [
    "# try, except and else\n",
    "\n",
    "try:\n",
    "    num = int(input(\"Enter a number: \"))\n",
    "    assert num % 2 == 0\n",
    "except:\n",
    "    print(\"Not an even number!\")\n",
    "else:\n",
    "    reciprocal = 1/num\n",
    "    print(reciprocal)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
